- name: Restart MySQL
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Flush Privileges 
  community.mysql.mysql_query: 
    login_db: repldB
    login_user: "{{mysql_login_user}}"
    login_unix_socket: "{{mysql_socket}}" 
    query: >
      FLUSH PRIVILEGES; 

