all:
  vars:
    ansible_port: 22
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: /home/annick/.ssh/cloud.key
  children:
    minikube:
      hosts:
        vm1:
          ansible_host: 172.28.101.129
          ansible_user: ubuntu
          http_port: 80
